### ISSUE TITLE
App doesn't work in landscape mode

### ISSUE THREAD

**Issue by cotibi** [PkmX/lcamera#145]
As the title states, the app doesn't go in landscape mode when turning phone (Nexus 5).

**Comment by jjjuande** [comment]
I have the same issue. (Nexus 5)

**Comment by ja-som** [comment]
Same on my Nexus5 :(
Whole UI of this camera is in portrait mode even if I hold my phone in landscape mode. Tried to take some pictures/videos but they are rotated, if I want to see them normally, I need to rotate them 90° CCW.

**Comment by cotibi** [comment]
As of today pictures are ok when taken in landscape mode but camera UI is still stuck in portrait mode upon rotating phone

**Comment by PkmX** [comment]
Yes, you gotta wait for me to implement the landscape UI. The orientation of images is a far more critical issue so I pushed this fix first.

**Comment by cotibi** [comment]
LOL I was sure you were working on it. I guess I was to fast to comment about it. My compliments for the great app.

**Comment by meshuggy** [comment]
I am still not able to record in landscape. Have I missed something?

**Comment by cotibi** [comment]
I belive that the developer abandoned the project. It's a shame...
